// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdlBD4sXyJBExSQp25uYL7aDVK-M_KOYc',
    appId: '1:362223279483:web:704ba6942dbd6069b331de',
    messagingSenderId: '362223279483',
    projectId: 'a14-cloud-messaging',
    authDomain: 'a14-cloud-messaging.firebaseapp.com',
    storageBucket: 'a14-cloud-messaging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUvwT0cVBfgB-YfJlDOYLXVbCyMX6h_wo',
    appId: '1:362223279483:android:3ba10505ef53e0bdb331de',
    messagingSenderId: '362223279483',
    projectId: 'a14-cloud-messaging',
    storageBucket: 'a14-cloud-messaging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHDX74E1SAMkaSOSOSPvsH056mqraGAoY',
    appId: '1:362223279483:ios:777da4d34d7f7abbb331de',
    messagingSenderId: '362223279483',
    projectId: 'a14-cloud-messaging',
    storageBucket: 'a14-cloud-messaging.firebasestorage.app',
    iosBundleId: 'com.example.a14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHDX74E1SAMkaSOSOSPvsH056mqraGAoY',
    appId: '1:362223279483:ios:777da4d34d7f7abbb331de',
    messagingSenderId: '362223279483',
    projectId: 'a14-cloud-messaging',
    storageBucket: 'a14-cloud-messaging.firebasestorage.app',
    iosBundleId: 'com.example.a14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdlBD4sXyJBExSQp25uYL7aDVK-M_KOYc',
    appId: '1:362223279483:web:80081e3f684d9bf8b331de',
    messagingSenderId: '362223279483',
    projectId: 'a14-cloud-messaging',
    authDomain: 'a14-cloud-messaging.firebaseapp.com',
    storageBucket: 'a14-cloud-messaging.firebasestorage.app',
  );
}
