// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0Hflx9RxUhdMtX0MYtYliYPtR3dRX6HA',
    appId: '1:784607382933:web:b8dc86de21c9d2ab247a9c',
    messagingSenderId: '784607382933',
    projectId: 'cloud-notification-9abed',
    authDomain: 'cloud-notification-9abed.firebaseapp.com',
    storageBucket: 'cloud-notification-9abed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlz9pjEDJrZhl4EafR-FTcy6ueMlnfD0Y',
    appId: '1:784607382933:android:463420cfe80b74ce247a9c',
    messagingSenderId: '784607382933',
    projectId: 'cloud-notification-9abed',
    storageBucket: 'cloud-notification-9abed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd1tTxAvS0d1nq90vrVcx7F7Orhb7SaVI',
    appId: '1:784607382933:ios:95f1cb971b43a44a247a9c',
    messagingSenderId: '784607382933',
    projectId: 'cloud-notification-9abed',
    storageBucket: 'cloud-notification-9abed.firebasestorage.app',
    iosBundleId: 'com.example.a14',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd1tTxAvS0d1nq90vrVcx7F7Orhb7SaVI',
    appId: '1:784607382933:ios:95f1cb971b43a44a247a9c',
    messagingSenderId: '784607382933',
    projectId: 'cloud-notification-9abed',
    storageBucket: 'cloud-notification-9abed.firebasestorage.app',
    iosBundleId: 'com.example.a14',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0Hflx9RxUhdMtX0MYtYliYPtR3dRX6HA',
    appId: '1:784607382933:web:1397eb01e2c6c842247a9c',
    messagingSenderId: '784607382933',
    projectId: 'cloud-notification-9abed',
    authDomain: 'cloud-notification-9abed.firebaseapp.com',
    storageBucket: 'cloud-notification-9abed.firebasestorage.app',
  );
}
