// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCulr9BGdxikn8SU7SXYuMVIljwhHo-zgo',
    appId: '1:409423752744:web:11b53a476d4a63852bcf1d',
    messagingSenderId: '409423752744',
    projectId: 'cw6-crud-d0b26',
    authDomain: 'cw6-crud-d0b26.firebaseapp.com',
    storageBucket: 'cw6-crud-d0b26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyMtK6YZDnZnD920H7mMWfyMk7Lm9UtQ',
    appId: '1:409423752744:android:9dabda6333eb1f7c2bcf1d',
    messagingSenderId: '409423752744',
    projectId: 'cw6-crud-d0b26',
    storageBucket: 'cw6-crud-d0b26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAunLqavm8rh7DFETkSg49NvjlKB2Tole8',
    appId: '1:409423752744:ios:4eeb8ff927efccff2bcf1d',
    messagingSenderId: '409423752744',
    projectId: 'cw6-crud-d0b26',
    storageBucket: 'cw6-crud-d0b26.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAunLqavm8rh7DFETkSg49NvjlKB2Tole8',
    appId: '1:409423752744:ios:4eeb8ff927efccff2bcf1d',
    messagingSenderId: '409423752744',
    projectId: 'cw6-crud-d0b26',
    storageBucket: 'cw6-crud-d0b26.firebasestorage.app',
    iosBundleId: 'com.example.cw6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCulr9BGdxikn8SU7SXYuMVIljwhHo-zgo',
    appId: '1:409423752744:web:7a277c09875a9c042bcf1d',
    messagingSenderId: '409423752744',
    projectId: 'cw6-crud-d0b26',
    authDomain: 'cw6-crud-d0b26.firebaseapp.com',
    storageBucket: 'cw6-crud-d0b26.firebasestorage.app',
  );
}
