// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyYtdSEalQ0uUHeJMSsR_TeJypdknGE98',
    appId: '1:558102328136:web:7e574d34c5f32704b9397d',
    messagingSenderId: '558102328136',
    projectId: 'myapp-90468',
    authDomain: 'myapp-90468.firebaseapp.com',
    storageBucket: 'myapp-90468.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_9LOdkx_mis0OKn4LuroMKHI6NIPFhE',
    appId: '1:558102328136:android:e54f52ed7a31ca02b9397d',
    messagingSenderId: '558102328136',
    projectId: 'myapp-90468',
    storageBucket: 'myapp-90468.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFg4wKkbMSviwetlbs6lPf2eqFIaSOSk',
    appId: '1:558102328136:ios:607347c9882f5ceab9397d',
    messagingSenderId: '558102328136',
    projectId: 'myapp-90468',
    storageBucket: 'myapp-90468.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFg4wKkbMSviwetlbs6lPf2eqFIaSOSk',
    appId: '1:558102328136:ios:607347c9882f5ceab9397d',
    messagingSenderId: '558102328136',
    projectId: 'myapp-90468',
    storageBucket: 'myapp-90468.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyYtdSEalQ0uUHeJMSsR_TeJypdknGE98',
    appId: '1:558102328136:web:778c91fc6467f528b9397d',
    messagingSenderId: '558102328136',
    projectId: 'myapp-90468',
    authDomain: 'myapp-90468.firebaseapp.com',
    storageBucket: 'myapp-90468.firebasestorage.app',
  );
}
