// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqTse3U0QrfaqAqqxYzAGmsSLYnx6FJjw',
    appId: '1:899319262276:web:0967942113a41b650aa011',
    messagingSenderId: '899319262276',
    projectId: 'hw4-splash-screen',
    authDomain: 'hw4-splash-screen.firebaseapp.com',
    storageBucket: 'hw4-splash-screen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFVcTmk2T1VPggNNqvqNLudgUQ1ONS24',
    appId: '1:899319262276:android:024444530472367f0aa011',
    messagingSenderId: '899319262276',
    projectId: 'hw4-splash-screen',
    storageBucket: 'hw4-splash-screen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBThBsU3CfMOVXphVoigzRUgynYNKNWk6s',
    appId: '1:899319262276:ios:046b6bd2ff862c610aa011',
    messagingSenderId: '899319262276',
    projectId: 'hw4-splash-screen',
    storageBucket: 'hw4-splash-screen.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBThBsU3CfMOVXphVoigzRUgynYNKNWk6s',
    appId: '1:899319262276:ios:046b6bd2ff862c610aa011',
    messagingSenderId: '899319262276',
    projectId: 'hw4-splash-screen',
    storageBucket: 'hw4-splash-screen.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqTse3U0QrfaqAqqxYzAGmsSLYnx6FJjw',
    appId: '1:899319262276:web:c17004ca43535dc90aa011',
    messagingSenderId: '899319262276',
    projectId: 'hw4-splash-screen',
    authDomain: 'hw4-splash-screen.firebaseapp.com',
    storageBucket: 'hw4-splash-screen.firebasestorage.app',
  );
}
